name: Shopee Scraper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 pytest
    - name: Check code formatting
      run: black . --exclude=venv --check
    - name: Check coding style
      run: flake8 ./